### ISSUE TITLE
Apparently bacter is not using the GPU to perform the calculations.

### ISSUE THREAD

**Issue by EnzoAndree** [tgvaughan/bacter#30]
Hello!

I have been testing bacter. However, it seems that the GPU is not used when running BEAST with the bacter module.

I have tried the other XML examples that comes with the BEAST package and it does use the GPU in those tests. It seems that only the bacter module does not use the GPU.

Can you confirm this behavior?

Best regards,
Enzo.

**Comment by tgvaughan** [comment]
Hi Enzo, this is correct.  I don't have much experience in using GPUs to speed up numerical calculations.  If you do, you're more than welcome to take a crack at implementing it yourself though - and I'd be happy of course to answer any questions you have along the way.

Tim
